# Generated by Django 5.1.7 on 2025-03-27 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('sourcelink', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='markedsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcelink.category'),
        ),
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language'),
        ),
        migrations.AddField(
            model_name='markedsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcelink.source'),
        ),
        migrations.AlterUniqueTogether(
            name='markedsource',
            unique_together={('user', 'source')},
        ),
    ]
