# Generated by Django 5.1.7 on 2025-03-27 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language'),
        ),
        migrations.AddField(
            model_name='favoriteword',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.translation'),
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.category'),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech'),
        ),
        migrations.AddField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteword',
            unique_together={('user', 'translation')},
        ),
    ]
